plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.146'
    id 'com.hypherionmc.modutils.modpublisher' version '2.2.2'
    id 'idea'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version + "+" + mc_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    // accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    exclude '.cache/'
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

repositories {
    mavenCentral()
    maven {
        name = "Cursemaven"
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Registrate"
        url = "https://maven.gegy.dev/releases"
        content {
            includeGroup "com.tterrag.registrate"
        }
    }
}

dependencies {
    implementation "org.appliedenergistics:appliedenergistics2:${ae2_version}"

    compileOnly "dev.emi:emi-neoforge:${emi_version}:api"
    localRuntime "dev.emi:emi-neoforge:${emi_version}"

    compileOnly "curse.maven:jade-324717:8591319"
    localRuntime "curse.maven:jade-324717:8591319"

    compileOnly "curse.maven:geore-530544:7966801"
    localRuntime "curse.maven:geore-530544:7966801"

    compileOnly "curse.maven:ex-pattern-provider-892005:8811572"
    localRuntime "curse.maven:ex-pattern-provider-892005:8811572"

    compileOnly "curse.maven:just-dire-things-1002348:7463040"
    localRuntime "curse.maven:just-dire-things-1002348:7463040"

    compileOnly "curse.maven:neo-eco-ae-extension-1460639:8463264"
    localRuntime "curse.maven:neo-eco-ae-extension-1460639:8463264"

    compileOnly "com.tterrag.registrate:Registrate:MC1.21.1-1.4.8"

    localRuntime "org.appliedenergistics:guideme:${guideme_version}"
    localRuntime "curse.maven:ldlib-626676:8813684"
    localRuntime "curse.maven:glodium-957920:5821676"
    localRuntime "curse.maven:mekanism-268560:7904058"
    localRuntime "curse.maven:super-factory-manager-306935:8370241"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mc_version          : mc_version,
            mc_version_range    : mc_version_range,
            neo_version         : neo_version,
            neo_version_range   : neo_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id,
            mod_name            : mod_name,
            mod_license         : mod_license,
            mod_version         : mod_version,
            mod_authors         : mod_authors,
            mod_description     : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

publisher {
    setCurseID("1316818")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}